### ISSUE TITLE
fish turns back into a normal vanilla minecraft fish in use with Luckperm

### ISSUE THREAD

**Issue by Nanichan20** [Kunfury-blep/Blep-Fishing#32]
I do not use worldguard plugin, but what i've notice is that if i change my role from default to let's say vip or a custom role, it breaks the blep fishing instead of it giving the blep's fish it gives default mc fish. not sure if i did anything wrong but that's what's been happening since i added the plugin, i am on minecraft V1.20.1

screenshot: https://imgur.com/a/svgKBfh

**Comment by Kunfury-blep** [comment]
I run with LuckPerms on my test servers and haven't experienced this issue before. Are you running with Area Permissions enabled in the plugin? If so that could be a cause of it if it is working for the default role and not the others.

If you'd like to discuss it further please feel free to join the [Community Discord](https://discord.com/invite/vuBCHngkFH)

**Comment by Nanichan20** [comment]
I am not running area permission on it's still set to false, i also found out that there is another plugin that isn't working so it might not be blep fishing, i might just need to re-add all the other plugin to see which one is causing the issue, since as soon as i have op my Forcepack and blep doesn't work. So sorry for the inconvenient, i've also joined the discord server
